apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: simple-statefulset
  labels:
    app: simple
spec:
  serviceName: simple-svc
  replicas: 3
  selector:
    matchLabels:
      app: simple-stateful
  template:
    metadata:
      labels:
        app: simple-stateful
    spec:
      containers:
      - name: myapp-container
        image: busybox
        command: ['sh', '-c', 'echo Hello, listening on port 2200 && nc -l -p 2200']