apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  labels:
    app: simple
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-deployment
  template:
    metadata:
      labels:
        app: simple-deployment
    spec:
      containers:
      - name: myapp-container
        image: busybox
        env:
        - name: LISTEN_PORT
          value: '2222'
        command: ['sh', '-c', 'echo Hello, listening on port $LISTEN_PORT && nc -l -p $LISTEN_PORT']